set nocompatible

filetype plugin indent on
syntax on

set number
set nobackup
set showmode " always show what mode we're currently editing in
set nowrap " don't wrap lines
set tabstop=4 " a tab is four spaces
set softtabstop=4 " when hitting <BS>, pretend like a tab is removed, even if spaces
set expandtab " expand tabs by default (overloadable per file type later)
set shiftwidth=4 " number of spaces to use for autoindenting
set shiftround " use multiple of shiftwidth when indenting with '<' and '>'
set backspace=indent,eol,start " allow backspacing over everything in insert mode
set autoindent " always set autoindenting on
set copyindent " copy the previous indentation on autoindenting
set showmatch " set show matching parenthesis
set ignorecase " ignore case when searching
set smartcase " ignore case if search pattern is all lowercase, case-sensitive otherwise
set mouse=a
set pastetoggle=<F2>
set modeline
set modelines=10

autocmd FileType typescript setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType yaml setlocal shiftwidth=2 softtabstop=2 expandtab

" Display tabs and trailing space visually
set list listchars=tab:\ \ ,trail:·

let mapleader=","
let g:mapleader=","

let g:csv_delim_test=",;|"
let g:csv_headerline=0

" Enable folding {{{
"augroup fdm
"    autocmd!
"    autocmd FileType vim    setlocal foldmethod=marker
"augroup END
" set foldlevel=1
" set foldlevelstart=99
" }}}

" Tabs - Navigation {{{
nnoremap th :tabfirst<CR>
nnoremap tj :tabprev<CR>
nnoremap tk :tabnext<CR>
nnoremap tl :tablast<CR>
" }}}

let g:ycm_rust_src_path="/usr/lib/rustlib/src/rust/src"
let g:ycm_autoclose_preview_window_after_completion = 1

if executable("rustup") && executable("rustc")
    let g:ycm_rust_src_path=expand(substitute(system("rustc --print sysroot"), '\n\+$', '', '') . "/lib/rustlib/src/rust/src")
endif

" vim: set sw=4 sts=4 et fdm=marker:
