#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0)"
	echo "    Pull changes into mercurial repository located at $TODO_DIR."
#	echo "    Always pulls from origin/master into local master branch."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"
hg pull
hg rebase -d tip
hg update
