[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]

[cargo-new]
name = "Constantin Nickel"
email = "constantin.nickel@gmail.com"

[alias]
c = "check"
cc = "clean"
ch = "check"
up = "update"
dd = "doc --no-deps"
ddp = "doc --no-deps --document-private-items"
ddo = "doc --no-deps --open"
ddpo = "doc --no-deps --document-private-items --open"
fmtc = "fmt -- --check"
fmtcdoc = "fmtc --config format_code_in_doc_comments=true"
fmtdoc = "fmt -- --config format_code_in_doc_comments=true"
ce = "check --example"
re = "run --example"
