prompt_order = [
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "line_break",
    "jobs",
    "character"
]

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[character]
symbol = ""
